#!/bin/bash

RUN_DIR=/var/vcap/sys/run/cloudstack_registry
LOG_DIR=/var/vcap/sys/log/cloudstack_registry
PIDFILE=$RUN_DIR/cloudstack_registry.pid
RUNAS=vcap

export PATH=/var/vcap/packages/ruby/bin:$PATH
export GEM_HOME=/var/vcap/packages/cloudstack_registry/gem_home

case $1 in

  start)
    mkdir -p $RUN_DIR $LOG_DIR
    chown -R $RUNAS:$RUNAS $RUN_DIR $LOG_DIR

    echo $$ > $PIDFILE

    chpst -u $RUNAS:$RUNAS \
      /var/vcap/packages/cloudstack_registry/bin/migrate \
      -c /var/vcap/jobs/cloudstack_registry/config/cloudstack_registry.yml \
      >>$LOG_DIR/migrate.stdout.log 2>>$LOG_DIR/migrate.stderr.log

    if [ $? -ne 0 ]; then
      echo "migration failed"
      exit 1
    fi

    exec chpst -u $RUNAS:$RUNAS \
      /var/vcap/packages/cloudstack_registry/bin/cloudstack_registry \
      -c /var/vcap/jobs/cloudstack_registry/config/cloudstack_registry.yml \
      >>$LOG_DIR/cloudstack_registry.stdout.log 2>>$LOG_DIR/cloudstack_registry.stderr.log
    ;;

  stop)
    PID=$(head -1 $PIDFILE)
    kill $PID
    while [ -e /proc/$PID ]; do sleep 0.1; done
    rm -f $PIDFILE
    ;;

  *)
  echo "Usage: cloudstack_registry_ctl {start|stop}" ;;
esac
exit 0
